config/routes.rb
Stream::Application.routes.draw do
  devise_for :users, :path_prefix => 'my', controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :users, :controller => "users"
  root :to => 'welcome#index'

  match "about" => 'welcome#about', via: :get
  match "anonymous" => 'songs#anonymous', via: :get

  resources :songs

  get 'tags/:tag', to: 'songs#index', as: :tag
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name, :audio, :info, :public, :tag_list

  acts_as_taggable

  #mount_uploader :audio, SongUploader
  #maybe later

  #two different users might pick the exact same name for a song, if it's generic
  validates :name, presence: true, uniqueness: {scope: :user_id}
  validates :audio, presence: true  

  auto_html_for :audio do
    html_escape
    image
    youtube(:width => 400, :height => 250)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    #current_ability defaults to read
    if params[:tag]
      @songs = Song.accessible_by(current_ability).tagged_with(params[:tag]).
      order(sort_column + ' ' + sort_direction).
      paginate(page: params[:page], per_page: 10)
    else
      @songs = Song.accessible_by(current_ability).order(sort_column + ' ' + sort_direction).
      paginate(page: params[:page], per_page: 10)
    end
  end

  def new
    @song = Song.new
  end

  def show
    @song = Song.find(params[:id])
    authorize! :read, @song, message: "This song is private."
  end

  def edit
    @song = Song.find(params[:id])
    authorize! :update, @song, message: "Memebers can edit their own songs only. Guests can't edit."
  end

  def create
    @song = Song.new(params[:song])

    #allows guests to upload, since can't .songs.build off a non-user
    @song.update_attribute(:user, current_user)

    if @song.save
      redirect_to(@song, notice: "Song was saved successfully.")
    else
      flash[:error] = "There was an error saving the song. Please try again."
      render :new
    end
  end

  def update
    @song = Song.find(params[:id])
    authorize! :update, @song, message: "You can't edit a song that doesn't belong to you. Guests can't edit."
    if @song.update_attributes(params[:song])
      redirect_to(proper_redirect_path_for(@song), notice: "\"#{@song.name}\" was updated successfully.")
    else
      flash[:error] = "There was an error saving the song. Please try again."
      render :edit
    end
  end

  def destroy
    @song = Song.find(params[:id])
    authorize! :destroy, @song, message: "Memebers can delete their own songs only. Guests can't delete."
    if @song.destroy
      if(proper_redirect_path_for(@song).match("\/songs\/[0-9]+"))
        #ugly hack to redirect to userpage if song was deleted from its show view
        #kind of arbitrary choice, would be "best" to send to "wherever they were before viewing song"
        redirect_to(current_user, notice: "\"#{@song.name}\" was deleted successfully.")
      else
        #otherwise, send to wherever user was last at
        redirect_to(proper_redirect_path_for(@song), notice: "\"#{@song.name}\" was deleted successfully.")
      end
    else
      flash[:error] = "There was an error deleting the song."
      render :show
    end
  end

  #probably don't need this ever
  def preview
    song = Song.new(params[:song])
    render :text => song.audio_html
  end

  def anonymous
    @anonymous_songs = Song.where(user_id: nil).order(sort_column + ' ' + sort_direction).
    paginate(page: params[:page], per_page: 10)
  end

  private

  def sort_column
    Song.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    if(["asc", "desc"].include?(params[:direction]))
      params[:direction] == "asc" ? "desc" : "asc"
    else
      "asc"
    end
  end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for song, html: { class: 'form-horizontal'} do |f| %>
  <% if song.errors.any? %>
    <div class="alert alert-block">
      <h4>There are <%= pluralize(song.errors.count, "error") %>.</h4>
      <ul>
        <% song.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= control_group_tag(song.errors[:name]) do %>
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  <% end %>
  <%= control_group_tag(song.errors[:audio]) do %>
    <%= f.label :audio, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :audio %>
    </div>
  <% end %>
  <%= control_group_tag(song.errors[:info]) do %>
    <%= f.label :info, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :info, rows: 8 %>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :tag_list, "Tags", class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :tag_list %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.label :public, class: 'checkbox' do %>
        <%= f.check_box :public %> Public song?
      <% end %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit "Save", class: 'btn' %>
    </div>
  </div>
<% end %>

app/views/songs/_song.html.erb
<div class="span6 song">
  <small>
  <%= content_tag :div, class: 'media', id: "song-#{song.id}" do %>
    <%= link_to '#', class: 'pull-left' do %>
      <%= link_to ("\##{song.id} #{song.name}"), song %>
      <br style="clear: both; height: 0px;" />
      <%= image_tag(song.user.avatar.tiny.url) if song.user && song.user.avatar? %>
      Uploaded <%= time_ago_in_words(song.created_at) %> ago
      <% if (song.user && (can? :read, song.user)) %>
        by <%= link_to song.user.name, song.user %>
      <% end %>
    <% end %>
  </small>  
    <p><%= song.audio_html %></p>
    <p><%= markdown song.info %></p> 
    Tags: <%= raw song.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
    <br style="clear: both; height: 0px;" />
    <% if can? :edit, song %>
      <%= link_to "Edit Song", edit_song_path(song), class: 'btn btn-mini btn-primary' %> 
    <% end %>
    <% if can? :destroy, song %>
      <%= link_to "Delete Song", [song], method: :delete, class: 'btn btn-mini btn-primary btn-danger',
      confirm: 'Are you sure you want to delete this song?' %> 
    <% end %>
  <% end %>
</div>

app/views/songs/anonymous.html.erb
<div class="row">
  <h1>The Anonymous Pool</h1>
  <p>
    Songs here are uploaded by guests and non-logged in users.</br>
    <%= sortable "name", "Sort A-Z" %> ●
    <%= sortable "created_at", "Sort by upload date" %>
  </p>
  <%= render @anonymous_songs %>
  <%= will_paginate @anonymous_songs %>
</div>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<div class="row">
  <div class="span4">
    <p>Guidelines for new songs:</p>
    <ul>
      <li>Make sure content is appropriate.</li>
      <li>All songs must have a unique name.</li>
      <li>Audio is the URL to a video (YouTube).</li>
      <li>Public songs can be viewed by anyone. Private songs can only be viewed by you.</li>
      <li>Separate tags by commas.</li>
    </ul>
  </div>
  <div class="span8">
    <%= render partial: 'form', locals: { song: @song } %>
  </div>
</div>

app/views/songs/index.html.erb
<div class="row">
  <h1>All Songs</h1>
  <p>
    Index of all songs visible to you. </br>
    <%= sortable "name", "Sort A-Z" %> ●
    <%= sortable "created_at", "Sort by upload date" %>
  </p>

  <div id="tag_cloud">
    Tag cloud: 
    <% tag_cloud Song.tag_counts, ["s", "m", "l"] do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <% end %>
  </div>
  <%= render @songs %>
  <%= will_paginate @songs %>
</div>

app/views/songs/new.html.erb
<h1>New Song</h1>

<div class="row">
  <div class="span4">
    <p>Guidelines for new songs:</p>
    <ul>
      <li>Make sure content is appropriate.</li>
      <li>All songs must have a unique name.</li>
      <li>Audio is the URL to a video (YouTube).</li>
      <li>Public songs can be viewed by anyone. Private songs can only be viewed by you.</li>
      <li>Separate tags by commas.</li>
    </ul>
  </div>
  <div class="span8">
    <%= render partial: 'form', locals: { song: @song } %>
  </div>
</div>

app/views/songs/show.html.erb
<div class="row span6">
  <% if can? :edit, @song %>
    <%= link_to "Edit Song", edit_song_path(@song), class: 'btn btn-mini btn-primary' %> 
  <% end %>
  <% if can? :destroy, @song %>
    <%= link_to "Delete Song", [@song], method: :delete, class: 'btn btn-mini btn-primary btn-danger',
    confirm: 'Are you sure you want to delete this song?' %> 
  <% end %>
  <small>
    <%= content_tag :div, class: 'media', id: "song-#{@song.id}" do %>
      <%= link_to '#', class: 'pull-left' do %>
        <%= link_to ("\##{@song.id} #{@song.name}"), @song %>
        <br style="clear: both; height: 0px;" />
        <%= image_tag(@song.user.avatar.tiny.url) if @song.user && @song.user.avatar? %>
        Uploaded <%= time_ago_in_words(@song.created_at) %> ago
        <% if (@song.user && (can? :read, @song.user)) %>
          by <%= link_to @song.user.name, @song.user %>
        <% end %>
      <% end %>
  </small>  
  <p><%= @song.audio_html %></p>
  <p><%= markdown @song.info %></p>
  Tags: <%= raw @song.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %> 
  <% end %>
</div>